# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-remoteproc-runtime-ext"
# NOTICE THE ESCAPED REGEX PREVENTING CROSS-LAYER MATCHING:
BBFILE_PATTERN_meta-remoteproc-runtime-ext = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-remoteproc-runtime-ext = "7"

LAYERDEPENDS_meta-remoteproc-runtime-ext = "core meta-remoteproc-runtime"
LAYERSERIES_COMPAT_meta-remoteproc-runtime-ext = "kirkstone"

# Override meta-remoteproc-runtime compatibility to match kirkstone
LAYERSERIES_COMPAT_meta-remoteproc-runtime = "kirkstone"
